# Generated by Django 4.2.3 on 2023-08-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='colour',
            new_name='color',
        ),
    ]
